name: Update Help Wanted

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  issues: write

jobs:
  update:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno run -A list-issues.ts
